<a href="https://colab.research.google.com/github/swapnilchavan0707/SwapMLDev/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
# Define a list with elements 1, 2, and 3
my_list = [1, 2, 3]

# Create a NumPy array from the list
my_numpy_array = np.array(my_list)


In [ ]:
# print output
# Print the NumPy array
print(my_numpy_array)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

# a =
# b =
# c =
# d =

import numpy as np

# a = A numpy array with one single integer 10
a = np.array(10)
print("Array 'a' (0-D array):")
print(a)
print("Dimension of 'a':", a.ndim)

# b = A numpy array passing a list having a list= [1,2,3]
b = np.array([1, 2, 3])
print("\nArray 'b' (1-D array):")
print(b)
print("Dimension of 'b':", b.ndim)

# c = A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements
c = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 'c' (2-D array):")
print(c)
print("Dimension of 'c':", c.ndim)

# d = A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("\nArray 'd' (3-D array):")
print(d)
print("Dimension of 'd':", d.ndim)


Array 'a' (0-D array):
10
Dimension of 'a': 0

Array 'b' (1-D array):
[1 2 3]
Dimension of 'b': 1

Array 'c' (2-D array):
[[1 2 3]
 [4 5 6]]
Dimension of 'c': 2

Array 'd' (3-D array):
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension of 'd': 3


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d
import numpy as np

# Recreate the arrays a, b, c, and d from the previous step
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Print the dimensions of each array using the ndim attribute
print("Dimension of array 'a':", a.ndim)
print("Dimension of array 'b':", b.ndim)
print("Dimension of array 'c':", c.ndim)
print("Dimension of array 'd':", d.ndim)




Dimension of array 'a': 0
Dimension of array 'b': 1
Dimension of array 'c': 2
Dimension of array 'd': 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d
import numpy as np

# Recreate the arrays a, b, c, and d from the previous step
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Print the shape of each array using the shape attribute
print("Shape of array 'a':", a.shape)
print("Shape of array 'b':", b.shape)
print("Shape of array 'c':", c.shape)
print("Shape of array 'd':", d.shape)





Shape of array 'a': ()
Shape of array 'b': (3,)
Shape of array 'c': (2, 3)
Shape of array 'd': (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
import numpy as np

# --- 1. Creating arrays of different dimensions ---
print("--- Creating NumPy Arrays with Different Dimensions ---")

# a: A numpy array with one single integer 10 (0-D array / Scalar)
a = np.array(10)
print("\nArray 'a':")
print(a)

# b: A numpy array passing a list having elements [1, 2, 3] (1-D array / Vector)
b = np.array([1, 2, 3])
print("\nArray 'b':")
print(b)

# c: A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements (2-D array / Matrix)
c = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 'c':")
print(c)

# d: A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements (3-D array / Tensor)
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("\nArray 'd':")
print(d)

# --- 2. Checking Dimensions using .ndim attribute ---
print("\n--- Checking Dimensions (.ndim) ---")
print(f"Dimension of array 'a': {a.ndim}")
print(f"Dimension of array 'b': {b.ndim}")
print(f"Dimension of array 'c': {c.ndim}")
print(f"Dimension of array 'd': {d.ndim}")

# --- 3. Checking Shapes using .shape attribute ---
print("\n--- Checking Shapes (.shape) ---")
print(f"Shape of array 'a': {a.shape}")
print(f"Shape of array 'b': {b.shape}")
print(f"Shape of array 'c': {c.shape}")
print(f"Shape of array 'd': {d.shape}")

# --- 4. Checking Data Types using .dtype attribute ---
print("\n--- Checking Data Types (.dtype) ---")
print(f"Data type of array 'c': {c.dtype}")
print(f"Data type of array 'd': {d.dtype}")




--- Creating NumPy Arrays with Different Dimensions ---

Array 'a':
10

Array 'b':
[1 2 3]

Array 'c':
[[1 2 3]
 [4 5 6]]

Array 'd':
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

--- Checking Dimensions (.ndim) ---
Dimension of array 'a': 0
Dimension of array 'b': 1
Dimension of array 'c': 2
Dimension of array 'd': 3

--- Checking Shapes (.shape) ---
Shape of array 'a': ()
Shape of array 'b': (3,)
Shape of array 'c': (2, 3)
Shape of array 'd': (2, 2, 3)

--- Checking Data Types (.dtype) ---
Data type of array 'c': int64
Data type of array 'd': int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
import numpy as np

# Recreate the NumPy arrays a and b
# These were defined in previous steps to represent a 0-D array (scalar) and a 1-D array (vector).
a = np.array(10)
b = np.array([1, 2, 3])

# Print the type of variable 'a' using the type() function
print(f"Type of variable 'a': {type(a)}")

# Print the type of variable 'b' using the type() function
print(f"Type of variable 'b': {type(b)}")





Type of variable 'a': <class 'numpy.ndarray'>
Type of variable 'b': <class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
# len(b)
import numpy as np

# Recreate the NumPy array b
b = np.array([1, 2, 3])

# Check the length of array b using len() function
length_of_b = len(b)

# Print the length
print(f"Length of array 'b': {length_of_b}")

Length of array 'b': 3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
# l1 =
# l2 =
# l3 =
# l4 =

import numpy as np

# Define list l1
l1 = [10, 20, 30]

# Define list l2
l2 = [40, 50, 60]

# Define numpy array l3 with l1 as its element
l3 = np.array(l1)

# Define numpy array l4 with l2 as its element
l4 = np.array(l2)

# Print all variables to verify
print(f"l1 (list): {l1}")
print(f"l2 (list): {l2}")
print(f"l3 (numpy array): {l3}")
print(f"l4 (numpy array): {l4}")


l1 (list): [10, 20, 30]
l2 (list): [40, 50, 60]
l3 (numpy array): [10 20 30]
l4 (numpy array): [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above
# Recreate lists l1 and l2
l1 = [10, 20, 30]
l2 = [40, 50, 60]

# Multiply each element of l1 with corresponding elements of l2 using list comprehension
# and use %timeit to measure the execution time.
# The result will be stored in a new list 'result_list_comp'.
%timeit result_list_comp = [l1[i] * l2[i] for i in range(len(l1))]



484 ns ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:
import numpy as np
import time

# Recreate NumPy arrays l3 and l4
l3 = np.array([10, 20, 30])
l4 = np.array([40, 50, 60])

# Measure time taken to multiply elements of l3 and l4 using NumPy's element-wise multiplication
start_time = time.time()
result_numpy_mult = l3 * l4
end_time = time.time()
time_taken_numpy_mult = end_time - start_time

print(f"Result of multiplication using NumPy arrays: {result_numpy_mult}")
print(f"Time taken for NumPy array multiplication: {time_taken_numpy_mult:.6f} seconds")


# and
import numpy as np
import time

# Recreate numpy arrays l3 and l4 (from previously defined l1 and l2)
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

# Measure time taken to multiply arrays l3 and l4
start_time = time.time()
result_numpy_multiply = l3 * l4
end_time = time.time()
time_taken_numpy_multiply = end_time - start_time

print(f"Result of multiplication using NumPy arrays: {result_numpy_multiply}")
print(f"Time taken for NumPy array multiplication: {time_taken_numpy_multiply:.6f} seconds")



Result of multiplication using NumPy arrays: [ 400 1000 1800]
Time taken for NumPy array multiplication: 0.000063 seconds
Result of multiplication using NumPy arrays: [ 400 1000 1800]
Time taken for NumPy array multiplication: 0.000051 seconds


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
import numpy as np

# Create a numpy array using arange with 1 and 11 as parameters
numpy_array_arange = np.arange(1, 11)

# Print the array
print(numpy_array_arange)



[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
import numpy as np

# --- NumPy Array Creation with arange() ---
print("--- Creating NumPy Arrays with arange() ---")

# 1. Create an array using arange with 1 and 11 as parameters
# This generates numbers starting from 1 up to (but not including) 11, with a default step of 1.
arr_arange_default_step = np.arange(1, 11)
print("\nArray created with np.arange(1, 11):")
print(arr_arange_default_step)

# 2. Create an array using arange with 1, 11, and 2 as parameters
# This generates numbers starting from 1 up to (but not including) 11, with a step of 2.
arr_arange_custom_step = np.arange(1, 11, 2)
print("\nArray created with np.arange(1, 11, 2):")
print(arr_arange_custom_step)



--- Creating NumPy Arrays with arange() ---

Array created with np.arange(1, 11):
[ 1  2  3  4  5  6  7  8  9 10]

Array created with np.arange(1, 11, 2):
[1 3 5 7 9]


In [ ]:
# create numpy array using eye function with 3 as passed parameter
import numpy as np

# Create a NumPy array using the eye function with 3 as the parameter
# This creates a 3x3 identity matrix.
arr_eye = np.eye(3)

# Print the created array
print(arr_eye)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=
import numpy as np

# Create a numpy array x with numbers between 1 to 16 using arange()
# To include 16, the stop parameter should be 17.
x = np.arange(1, 17)

# Print the array x
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Reshape x with 2 rows and 8 columns
import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x with 2 rows and 8 columns
x_reshaped = x.reshape(2, 8)

# Print the reshaped array
print(x_reshaped)

# and
import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x with 2 rows and 8 columns
x_reshaped = x.reshape(2, 8)

# Print the reshaped array
print(x_reshaped)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x with dimension (2, 4, 2)
# This means 2 arrays, each containing 4 arrays, with each of those 4 arrays having 2 elements.
x_reshaped_3d = x.reshape(2, 4, 2)

# Print the reshaped array
print(x_reshaped_3d)

import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x with dimensions (2, 4, 2)
# This means 2 arrays, each containing 4 arrays, with each of those having 2 elements.
x_reshaped_3d = x.reshape(2, 4, 2)

# Print the reshaped array
print(x_reshaped_3d)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x into a 2-D numpy array with shape 4*4 using unknown dimension (-1)
# Here, we specify 4 rows, and NumPy will automatically calculate the number of columns.
x_reshaped_unknown_dim = x.reshape(4, -1)

# Print the reshaped array
print(x_reshaped_unknown_dim)

import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x into a 2-D numpy array with shape 4x4 using an unknown dimension
# Using -1 allows NumPy to automatically calculate the size of that dimension.
x_reshaped_unknown_dim = x.reshape(4, -1) # or x.reshape(-1, 4)

# Print the reshaped array
print(x_reshaped_unknown_dim)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# y=


# print y

import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x into a 3-D numpy array with 2 arrays that contains 4 arrays, using unknown dimension
# The shape will be (2, 4, -1), where -1 will be automatically calculated as 2 (since 2*4*2 = 16)
y = x.reshape(2, 4, -1)

# Print y
print(y)

import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x into a 3-D numpy array with 2 arrays that contains 4 arrays (unknown last dimension)
# This means the shape will be (2, 4, -1), and NumPy will calculate the last dimension (which will be 2).
y = x.reshape(2, 4, -1)

# Print y
print(y)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Flattening y
import numpy as np

# Recreate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Recreate numpy array y (x reshaped into 3-D)
y = x.reshape(2, 4, -1) # This results in shape (2, 4, 2)

# Flattening y
y_flattened = y.flatten()

# Print the flattened array
print(y_flattened)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Create an array a with all even numbers between 1 to 17
# a =


# print a

import numpy as np

# Create an array 'a' with all even numbers between 1 to 17
# Start from 2 (first even number), go up to (but not including) 18 to include 16, step by 2.
a = np.arange(2, 18, 2)

# Print the array a
print(a)

[ 2  4  6  8 10 12 14 16]


In [ ]:
# Get third element in array a
import numpy as np

# Recreate array 'a' with all even numbers between 1 to 17
a = np.arange(2, 18, 2)

# Get the third element in array 'a' (which is at index 2 due to 0-based indexing)
third_element = a[2]

# Print the third element
print(f"The third element in array 'a' is: {third_element}")

import numpy as np

# Recreate array a with all even numbers between 1 to 17
a = np.arange(2, 18, 2)

# Get the third element in array a (index 2 due to 0-based indexing)
third_element = a[2]

# Print the third element
print(f"The third element in array 'a' is: {third_element}")

The third element in array 'a' is: 6
The third element in array 'a' is: 6


In [ ]:
#Print 3rd, 5th, and 7th element in array a
import numpy as np

# Recreate array a with all even numbers between 1 to 17
a = np.arange(2, 18, 2)

# Print 3rd, 5th, and 7th element in array a using fancy indexing
# 3rd element -> index 2
# 5th element -> index 4
# 7th element -> index 6
selected_elements = a[[2, 4, 6]]

print(f"The 3rd, 5th, and 7th elements in array 'a' are: {selected_elements}")

import numpy as np

# Recreate array a with all even numbers between 1 to 17
a = np.arange(2, 18, 2)

# Print 3rd, 5th, and 7th element in array a
# Using 0-based indexing:
# 3rd element is at index 2
# 5th element is at index 4
# 7th element is at index 6
selected_elements = a[[2, 4, 6]]

print(f"The 3rd, 5th, and 7th elements in array 'a' are: {selected_elements}")


The 3rd, 5th, and 7th elements in array 'a' are: [ 6 10 14]
The 3rd, 5th, and 7th elements in array 'a' are: [ 6 10 14]


Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
# a =
import numpy as np

# Define a 2-D array 'a' with the given elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the array 'a'
print(a)

import numpy as np

# Define a 2-D array 'a' with the specified elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the array a
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print the 3rd element from the 3rd row of a
import numpy as np

# Recreate the 2-D array 'a'
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the 3rd element from the 3rd row of 'a'
# (index 2 for row, index 2 for column due to 0-based indexing)
element = a[2, 2]

print(f"The 3rd element from the 3rd row of 'a' is: {element}")


The 3rd element from the 3rd row of 'a' is: 9


Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# b =
import numpy as np

# --- 1. Defining a 2-D array 'a' ---
print("--- Defining a 2-D Array 'a' ---")
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Array 'a':")
print(a)

# --- 2. Printing a specific element from array 'a' ---
print("\n--- Accessing an Element from Array 'a' ---")
# Print the 3rd element from the 3rd row of 'a' (using 0-based indexing: a[row_index, col_index])
element_a_3rd_row_3rd_col = a[2, 2]
print(f"The 3rd element from the 3rd row of 'a' is: {element_a_3rd_row_3rd_col}")

# --- 3. Defining a 3-D array 'b' ---
print("\n--- Defining a 3-D Array 'b' ---")
b = np.array([[[1, 2, 3],
               [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]]])
print("Array 'b':")
print(b)


--- Defining a 2-D Array 'a' ---
Array 'a':
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Accessing an Element from Array 'a' ---
The 3rd element from the 3rd row of 'a' is: 9

--- Defining a 3-D Array 'b' ---
Array 'b':
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
import numpy as np

# Recreate the 3-D array 'b'
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the 3rd element from the 2nd array (index 1), which is the 1st nested list (index 0)
# of that 2nd array, and then the 3rd element (index 2) from that list.
# This translates to b[1][0][2] in 0-based indexing.
element = b[1, 0, 2]

print(f"The element is: {element}")


import numpy as np

# Recreate the 3-D array 'b'
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the 3rd element from the 2nd list (index 1 for the first dimension),
# which is the 1st list in that nested part (index 0 for the second dimension),
# and the 3rd element in that innermost list (index 2 for the third dimension).
# This corresponds to b[1, 0, 2]
element = b[1, 0, 2]

print(f"The specified element from array 'b' is: {element}")



The element is: 9
The specified element from array 'b' is: 9


In [ ]:
# Create 1D array

# arr=

import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Print the array to verify
print(arr)



[1 2 3 4 5]


In [ ]:
# Slice elements from 1st to 5th element from the following array:
import numpy as np

# --- 1. Create a 1D NumPy array ---
print("--- Creating a 1D Array ---")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # Extended for better slicing demonstration
print("Original 1D array 'arr':")
print(arr)

# --- 2. Slice elements from 1st to 5th element ---
print("\n--- Slicing Elements ---")
# To slice from the 1st element (index 0) up to the 5th element (index 4),
# we use the slice [0:5] as the end index is exclusive.
sliced_arr = arr[0:5]
print("Elements sliced from 1st to 5th position:")
print(sliced_arr)




--- Creating a 1D Array ---
Original 1D array 'arr':
[ 1  2  3  4  5  6  7  8  9 10]

--- Slicing Elements ---
Elements sliced from 1st to 5th position:
[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array:
import numpy as np

# --- 1. Create a 1D NumPy array ---
print("--- Creating a 1D Array ---")
# Using an array with more elements for clearer slicing examples
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original 1D array 'arr':")
print(arr)

# --- 2. Slice elements from 1st to 5th element ---
print("\n--- Slicing Elements (1st to 5th) ---")
# To slice from the 1st element (index 0) up to the 5th element (index 4),
# we use the slice [0:5] as the end index is exclusive.
sliced_arr_0_to_4 = arr[0:5]
print("Elements sliced from 1st to 5th position:")
print(sliced_arr_0_to_4)

# --- 3. Slice elements from index 5 to the end of the array ---
print("\n--- Slicing Elements (from index 5 to end) ---")
# To slice from index 5 to the end, we omit the end index: [5:]
sliced_arr_from_5 = arr[5:]
print("Elements sliced from index 5 to the end:")
print(sliced_arr_from_5)



--- Creating a 1D Array ---
Original 1D array 'arr':
[ 1  2  3  4  5  6  7  8  9 10]

--- Slicing Elements (1st to 5th) ---
Elements sliced from 1st to 5th position:
[1 2 3 4 5]

--- Slicing Elements (from index 5 to end) ---
Elements sliced from index 5 to the end:
[ 6  7  8  9 10]


In [ ]:
# Slice elements from the beginning to index 5 (not included):
import numpy as np

# --- 1. Create a 1D NumPy array ---
print("--- Creating a 1D Array ---")
# Using an array with more elements for clearer slicing examples
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original 1D array 'arr':")
print(arr)

# --- 2. Slice elements from 1st to 5th element (index 0 to 4) ---
print("\n--- Slicing Elements (1st to 5th position) ---")
# [start:end] where end is exclusive.
sliced_arr_0_to_4 = arr[0:5]
print("Elements sliced from 1st to 5th position (indices 0-4):")
print(sliced_arr_0_to_4)

# --- 3. Slice elements from index 5 to the end of the array ---
print("\n--- Slicing Elements (from index 5 to end) ---")
# [start:] where the end is implicitly the last element.
sliced_arr_from_5 = arr[5:]
print("Elements sliced from index 5 to the end:")
print(sliced_arr_from_5)

# --- 4. Slice elements from the beginning to index 5 (not included) ---
print("\n--- Slicing Elements (from beginning to index 5 - exclusive) ---")
# [:end] where the start is implicitly the first element, and end is exclusive.
sliced_arr_to_5 = arr[:5]
print("Elements sliced from the beginning to index 5 (not included):")
print(sliced_arr_to_5)




--- Creating a 1D Array ---
Original 1D array 'arr':
[ 1  2  3  4  5  6  7  8  9 10]

--- Slicing Elements (1st to 5th position) ---
Elements sliced from 1st to 5th position (indices 0-4):
[1 2 3 4 5]

--- Slicing Elements (from index 5 to end) ---
Elements sliced from index 5 to the end:
[ 6  7  8  9 10]

--- Slicing Elements (from beginning to index 5 - exclusive) ---
Elements sliced from the beginning to index 5 (not included):
[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:
import numpy as np

# --- 1. Create a 1D NumPy array ---
print("--- Creating a 1D Array ---")
# Using an array with more elements for clearer slicing examples
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original 1D array 'arr':")
print(arr)

# --- 2. Slice elements from 1st to 5th element (index 0 to 4) ---
print("\n--- Slicing Elements (1st to 5th position) ---")
# [start:end] where end is exclusive.
sliced_arr_0_to_4 = arr[0:5]
print("Elements sliced from 1st to 5th position (indices 0-4):")
print(sliced_arr_0_to_4)

# --- 3. Slice elements from index 5 to the end of the array ---
print("\n--- Slicing Elements (from index 5 to end) ---")
# [start:] where the end is implicitly the last element.
sliced_arr_from_5 = arr[5:]
print("Elements sliced from index 5 to the end:")
print(sliced_arr_from_5)

# --- 4. Slice elements from the beginning to index 5 (not included) ---
print("\n--- Slicing Elements (from beginning to index 5 - exclusive) ---")
# [:end] where the start is implicitly the first element, and end is exclusive.
sliced_arr_to_5 = arr[:5]
print("Elements sliced from the beginning to index 5 (not included):")
print(sliced_arr_to_5)

# --- 5. Slice elements with a step value (every other element from index 1 to 7) ---
print("\n--- Slicing Elements with a Step Value ---")
# [start:end:step]
# From index 1, up to (but not including) index 7, taking every 2nd element.
sliced_with_step = arr[1:7:2]
print("Every other element from index 1 to index 7 (exclusive):")
print(sliced_with_step)



--- Creating a 1D Array ---
Original 1D array 'arr':
[ 1  2  3  4  5  6  7  8  9 10]

--- Slicing Elements (1st to 5th position) ---
Elements sliced from 1st to 5th position (indices 0-4):
[1 2 3 4 5]

--- Slicing Elements (from index 5 to end) ---
Elements sliced from index 5 to the end:
[ 6  7  8  9 10]

--- Slicing Elements (from beginning to index 5 - exclusive) ---
Elements sliced from the beginning to index 5 (not included):
[1 2 3 4 5]

--- Slicing Elements with a Step Value ---
Every other element from index 1 to index 7 (exclusive):
[2 4 6]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:
import numpy as np

# --- 1. Create a 1D NumPy array ---
print("--- Creating a 1D Array ---")
# Using an array with more elements for clearer slicing examples
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original 1D array 'arr':")
print(arr)

# --- 2. Slice elements from 1st to 5th element (index 0 to 4) ---
print("\n--- Slicing Elements (1st to 5th position) ---")
# [start:end] where end is exclusive.
sliced_arr_0_to_4 = arr[0:5]
print("Elements sliced from 1st to 5th position (indices 0-4):")
print(sliced_arr_0_to_4)

# --- 3. Slice elements from index 5 to the end of the array ---
print("\n--- Slicing Elements (from index 5 to end) ---")
# [start:] where the end is implicitly the last element.
sliced_arr_from_5 = arr[5:]
print("Elements sliced from index 5 to the end:")
print(sliced_arr_from_5)

# --- 4. Slice elements from the beginning to index 5 (not included) ---
print("\n--- Slicing Elements (from beginning to index 5 - exclusive) ---")
# [:end] where the start is implicitly the first element, and end is exclusive.
sliced_arr_to_5 = arr[:5]
print("Elements sliced from the beginning to index 5 (not included):")
print(sliced_arr_to_5)

# --- 5. Slice elements with a step value (every other element from index 1 to 7) ---
print("\n--- Slicing Elements with a Step Value (Partial Array) ---")
# [start:end:step]
# From index 1, up to (but not including) index 7, taking every 2nd element.
sliced_with_step_partial = arr[1:7:2]
print("Every other element from index 1 to index 7 (exclusive):")
print(sliced_with_step_partial)

# --- 6. Return every other element from the entire array ---
print("\n--- Slicing Elements with a Step Value (Entire Array) ---")
# [::step]
# From the beginning to the end, taking every 2nd element.
sliced_every_other_entire = arr[::2]
print("Every other element from the entire array:")
print(sliced_every_other_entire)



--- Creating a 1D Array ---
Original 1D array 'arr':
[ 1  2  3  4  5  6  7  8  9 10]

--- Slicing Elements (1st to 5th position) ---
Elements sliced from 1st to 5th position (indices 0-4):
[1 2 3 4 5]

--- Slicing Elements (from index 5 to end) ---
Elements sliced from index 5 to the end:
[ 6  7  8  9 10]

--- Slicing Elements (from beginning to index 5 - exclusive) ---
Elements sliced from the beginning to index 5 (not included):
[1 2 3 4 5]

--- Slicing Elements with a Step Value (Partial Array) ---
Every other element from index 1 to index 7 (exclusive):
[2 4 6]

--- Slicing Elements with a Step Value (Entire Array) ---
Every other element from the entire array:
[1 3 5 7 9]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [ ]:
# Print array a
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
import numpy as np

# --- 1. Define our 2-D array 'a' ---
print("--- Defining a 2-D Array 'a' ---")
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Our 2-D array 'a':")
print(a)

# --- 2. Slice elements based on the instruction ---
print("\n--- Slicing Elements from 2-D Array 'a' ---")
# Interpretation: "From the third element" refers to the third row (index 2).
# "slice elements from index 1 to index 5 (not included)" refers to column indices from 1 to 4.
# Since the row a[2] is [7, 8, 9], indexing a[2, 1:5] will effectively slice [7, 8, 9] from index 1 up to the end.
sliced_elements = a[2, 1:5]

print("Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):")
print(sliced_elements)



--- Defining a 2-D Array 'a' ---
Our 2-D array 'a':
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Slicing Elements from 2-D Array 'a' ---
Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):
[8 9]


In [ ]:
# In array 'a' print index 2 from all the elements :
import numpy as np

# --- 1. Define our 2-D array 'a' ---
print("--- Defining a 2-D Array 'a' ---")
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Our 2-D array 'a':")
print(a)

# --- 2. Slice elements based on a complex instruction (from previous turn) ---
print("\n--- Slicing Elements from 2-D Array 'a' (Complex Slice) ---")
# Interpretation: "From the third element" refers to the third row (index 2).
# "slice elements from index 1 to index 5 (not included)" refers to column indices from 1 to 4.
sliced_elements_complex = a[2, 1:5]
print("Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):")
print(sliced_elements_complex)

# --- 3. Print index 2 from all elements (i.e., the third column) ---
print("\n--- Slicing Elements (Getting a Specific Column) ---")
# To get the element at index 2 (the third element) from all rows,
# we use the slicing a[:, 2]. The ':' means "all rows".
column_at_index_2 = a[:, 2]
print("Elements at index 2 from all rows in array 'a' (the third column):")
print(column_at_index_2)



--- Defining a 2-D Array 'a' ---
Our 2-D array 'a':
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Slicing Elements from 2-D Array 'a' (Complex Slice) ---
Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):
[8 9]

--- Slicing Elements (Getting a Specific Column) ---
Elements at index 2 from all rows in array 'a' (the third column):
[3 6 9]


In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
import numpy as np

# --- 1. Define our 2-D array 'a' ---
print("--- Defining a 2-D Array 'a' ---")
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Our 2-D array 'a':")
print(a)

# --- 2. Slice elements based on a complex instruction (from previous turn) ---
print("\n--- Slicing Elements from 2-D Array 'a' (Complex Slice) ---")
# Interpretation: "From the third element" refers to the third row (index 2).
# "slice elements from index 1 to index 5 (not included)" refers to column indices from 1 to 4.
sliced_elements_complex = a[2, 1:5]
print("Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):")
print(sliced_elements_complex)

# --- 3. Print index 2 from all elements (i.e., the third column) ---
print("\n--- Slicing Elements (Getting a Specific Column) ---")
# To get the element at index 2 (the third element) from all rows,
# we use the slicing a[:, 2]. The ':' means "all rows".
column_at_index_2 = a[:, 2]
print("Elements at index 2 from all rows in array 'a' (the third column):")
print(column_at_index_2)

# --- 4. From all the elements in 'a', slice index 1 till end (columns) ---
print("\n--- Slicing Elements (All Rows, from Column Index 1 to End) ---")
# This means selecting all rows (:) and then slicing columns from index 1 to the end (1:).
sliced_2d_array_all_rows_col_1_to_end = a[:, 1:]
print("Sliced 2-D array (from all rows, column index 1 till end):")
print(sliced_2d_array_all_rows_col_1_to_end)



--- Defining a 2-D Array 'a' ---
Our 2-D array 'a':
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Slicing Elements from 2-D Array 'a' (Complex Slice) ---
Elements sliced from the third row (index 2), from column index 1 to 5 (exclusive):
[8 9]

--- Slicing Elements (Getting a Specific Column) ---
Elements at index 2 from all rows in array 'a' (the third column):
[3 6 9]

--- Slicing Elements (All Rows, from Column Index 1 to End) ---
Sliced 2-D array (from all rows, column index 1 till end):
[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [ ]:
# x1=
import numpy as np

# Create an original NumPy array
x1 = np.array([10, 20, 30, 40, 50])
print(f"Original x1: {x1}")

# Create an explicit COPY of x1 using .copy()
x2 = x1.copy()
print(f"x2 (a copy): {x2}")

# Check if they are the same object (should be False)
print(f"Are x1 and x2 the same object? {x1 is x2}")

# Check if they share the same data in memory (should be False for a copy)
print(f"Do x1 and x2 share the same memory? {np.shares_memory(x1, x2)}")
print(f"Does x2 own its data? {x2.flags['OWNDATA']}") # Should be True for a copy

# Now, modify an element in x2 (the copy)
x2[0] = 999
x2[1] = 888

print(f"\nModified x2 (the copy): {x2}")
print(f"Original x1 after modifying x2: {x1}") # x1 remains unchanged!

# Modify an element in x1 (the original)
x1[2] = 777
print(f"\nModified x1 (the original): {x1}")
print(f"x2 after modifying x1: {x2}") # x2 remains unchanged!


Original x1: [10 20 30 40 50]
x2 (a copy): [10 20 30 40 50]
Are x1 and x2 the same object? False
Do x1 and x2 share the same memory? False
Does x2 own its data? True

Modified x2 (the copy): [999 888  30  40  50]
Original x1 after modifying x2: [10 20 30 40 50]

Modified x1 (the original): [ 10  20 777  40  50]
x2 after modifying x1: [999 888  30  40  50]


In [ ]:
# assign x2 = x1
import numpy as np

# Create the original array
x1 = np.array([10, 20, 30, 40, 50])
print(f"Original x1: {x1}")

# Assign x2 = x1, creating a view
x2 = x1
print(f"x2 after assignment (x2 = x1): {x2}")

# Let's confirm they are indeed the same object (pointing to the same memory)
print(f"Are x1 and x2 the same object? {x1 is x2}")
print(f"Do x1 and x2 share the same memory? {np.shares_memory(x1, x2)}")

# Now, let's modify an element in x2
x2[0] = 999
x2[1] = 888

print(f"\nModified x2: {x2}")
print(f"x1 after modifying x2: {x1}") # See! x1 also changed.

# And if we modify x1
x1[2] = 777
print(f"\nModified x1: {x1}")
print(f"x2 after modifying x1: {x2}") # x2 changes too!


Original x1: [10 20 30 40 50]
x2 after assignment (x2 = x1): [10 20 30 40 50]
Are x1 and x2 the same object? True
Do x1 and x2 share the same memory? True

Modified x2: [999 888  30  40  50]
x1 after modifying x2: [999 888  30  40  50]

Modified x1: [999 888 777  40  50]
x2 after modifying x1: [999 888 777  40  50]


In [ ]:
#print x1 and x2
import numpy as np

# Recreate the initial scenario:
# Assuming x1 was created as a numpy array and then x2 was assigned x1
x1 = np.array([10, 20, 30, 40, 50])
x2 = x1 # x2 is now a view of x1

# As per the previous step, let's also apply a modification to x2
# to clearly demonstrate the view behavior when printing
x2[0] = 999
x2[1] = 888

# Print x1 and x2
print(f"Value of x1: {x1}")
print(f"Value of x2: {x2}")

# Confirming they are the same object and share memory
print(f"Is x1 the same object as x2? {x1 is x2}")
print(f"Do x1 and x2 share the same memory? {np.shares_memory(x1, x2)}")

import numpy as np

# Recreate the scenario where x2 is a view of x1
x1 = np.array([10, 20, 30, 40, 50])
# Modify x1 to reflect potential previous changes (e.g., if x2[0]=10 was done on a previous state)
x1[0] = 10 # This ensures x1 starts with 10 if there was a previous modification to x2
x2 = x1

# Print x1 and x2
print(f"Value of x1: {x1}")
print(f"Value of x2: {x2}")

# Confirm they are the same object and share memory
print(f"Is x1 the same object as x2? {x1 is x2}")
print(f"Do x1 and x2 share the same memory? {np.shares_memory(x1, x2)}")



Value of x1: [999 888  30  40  50]
Value of x2: [999 888  30  40  50]
Is x1 the same object as x2? True
Do x1 and x2 share the same memory? True
Value of x1: [10 20 30 40 50]
Value of x2: [10 20 30 40 50]
Is x1 the same object as x2? True
Do x1 and x2 share the same memory? True


Ok now you have seen that both of them are same

In [ ]:
# change 1st element of x2 as 10
import numpy as np

# Recreate the scenario where x2 is a view of x1
# Assuming original x1 was [10, 20, 30, 40, 50] before any modifications
x1 = np.array([10, 20, 30, 40, 50])
x2 = x1 # x2 is now a view of x1

print(f"Before change: x1 = {x1}, x2 = {x2}")

# Change the 1st element (index 0) of x2 to 10
x2[0] = 10

print(f"After change:  x1 = {x1}, x2 = {x2}")

# Verify that x1 also changed
print("\nNotice that changing x2 also changed x1, because x2 is a view of x1.")



Before change: x1 = [10 20 30 40 50], x2 = [10 20 30 40 50]
After change:  x1 = [10 20 30 40 50], x2 = [10 20 30 40 50]

Notice that changing x2 also changed x1, because x2 is a view of x1.


In [ ]:
#Again print x1 and x2
import numpy as np

# Recreate the scenario just before printing
# Assuming the last state was x1 = [10 20 30 40 50] and x2 = x1,
# and then x2[0] was changed to 10.
x1 = np.array([10, 20, 30, 40, 50])
x2 = x1
x2[0] = 10 # Applying the change that happened in the last step

# Print x1 and x2 again
print(f"Value of x1: {x1}")
print(f"Value of x2: {x2}")

# Just to reconfirm the view relationship
print(f"Is x1 the same object as x2? {x1 is x2}")
print(f"Do x1 and x2 share the same memory? {np.shares_memory(x1, x2)}")



Value of x1: [10 20 30 40 50]
Value of x2: [10 20 30 40 50]
Is x1 the same object as x2? True
Do x1 and x2 share the same memory? True


In [ ]:
# Check memory share between x1 and x2
import numpy as np

# --- 1. Demonstrating a VIEW (shared data) ---
print("--- Demonstrating a VIEW (Shared Data) ---")

# Create the original array (x1)
x1_original = np.array([1, 2, 3, 4, 5])
print(f"Initial x1_original: {x1_original}")

# Create x2 as a VIEW of x1_original (using direct assignment)
# x2 now points to the same data as x1_original
x2_view = x1_original
print(f"x2_view (assigned as x1_original): {x2_view}")

# Verify if they are the exact same object (should be True)
print(f"Are x1_original and x2_view the same object? {x1_original is x2_view}")

# Check if they share the same underlying memory (should be True)
print(f"Do x1_original and x2_view share memory? {np.shares_memory(x1_original, x2_view)}")

# Modify an element in the view (x2_view)
print("\n--- Modifying the View ---")
x2_view[0] = 99
print(f"x2_view after modification: {x2_view}")
print(f"x1_original after x2_view modification: {x1_original}") # x1_original also changed!

# --- 2. Demonstrating a COPY (independent data) ---
print("\n--- Demonstrating a COPY (Independent Data) ---")

# Create a new original array
x3_original = np.array([10, 20, 30, 40, 50])
print(f"Initial x3_original: {x3_original}")

# Create x4 as a COPY of x3_original (using .copy() method)
# x4 has its own independent data
x4_copy = x3_original.copy()
print(f"x4_copy (created with .copy()): {x4_copy}")

# Verify if they are the exact same object (should be False)
print(f"Are x3_original and x4_copy the same object? {x3_original is x4_copy}")

# Check if they share the same underlying memory (should be False)
print(f"Do x3_original and x4_copy share memory? {np.shares_memory(x3_original, x4_copy)}")

# Modify an element in the copy (x4_copy)
print("\n--- Modifying the Copy ---")
x4_copy[0] = 999
print(f"x4_copy after modification: {x4_copy}")
print(f"x3_original after x4_copy modification: {x3_original}") # x3_original remains unchanged!


--- Demonstrating a VIEW (Shared Data) ---
Initial x1_original: [1 2 3 4 5]
x2_view (assigned as x1_original): [1 2 3 4 5]
Are x1_original and x2_view the same object? True
Do x1_original and x2_view share memory? True

--- Modifying the View ---
x2_view after modification: [99  2  3  4  5]
x1_original after x2_view modification: [99  2  3  4  5]

--- Demonstrating a COPY (Independent Data) ---
Initial x3_original: [10 20 30 40 50]
x4_copy (created with .copy()): [10 20 30 40 50]
Are x3_original and x4_copy the same object? False
Do x3_original and x4_copy share memory? False

--- Modifying the Copy ---
x4_copy after modification: [999  20  30  40  50]
x3_original after x4_copy modification: [10 20 30 40 50]


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:
# Create a view of x1 and store it in x3.
# x3 =
import numpy as np

# Create an original array x1
x1 = np.array([10, 20, 30, 40, 50])
print(f"Original x1: {x1}")

# Create a view of x1 using the .view() method and store it in x3
x3 = x1.view()
print(f"x3 (a view created with .view()): {x3}")

# Check if they share the same memory
print(f"Do x1 and x3 share the same memory? {np.shares_memory(x1, x3)}")

# Check if they are the exact same object (should be False, unlike direct assignment)
print(f"Are x1 and x3 the same object? {x1 is x3}") # Expected False for .view()

# Modify an element in x3 (the view)
x3[0] = 999
x3[1] = 888

print(f"\nModified x3: {x3}")
print(f"Original x1 after modifying x3: {x1}") # x1 should also change

Original x1: [10 20 30 40 50]
x3 (a view created with .view()): [10 20 30 40 50]
Do x1 and x3 share the same memory? True
Are x1 and x3 the same object? False

Modified x3: [999 888  30  40  50]
Original x1 after modifying x3: [999 888  30  40  50]


In [ ]:
# Again check memory share between x1 and x3
import numpy as np

# Recreate the state of x1 and x3 after the previous modification
x1 = np.array([10, 20, 30, 40, 50]) # Initial state for clarity
x3 = x1.view()                    # Create the view
x3[0] = 999                       # Apply previous modification
x3[1] = 888                       # Apply previous modification

print(f"Current x1: {x1}")
print(f"Current x3: {x3}")

# Check if x1 and x3 share memory
shares_memory = np.shares_memory(x1, x3)
print(f"Do x1 and x3 share memory? {shares_memory}")



Current x1: [999 888  30  40  50]
Current x3: [999 888  30  40  50]
Do x1 and x3 share memory? True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:
#Change 1st element of x3=100
import numpy as np

# Recreate the state where x3 is a view of x1, and they currently hold
# the values [999 888  30  40  50] from our last interaction.
x1 = np.array([999, 888, 30, 40, 50])
x3 = x1.view()

print(f"Before change: x1 = {x1}")
print(f"Before change: x3 = {x3}")

# Change the 1st element (index 0) of x3 to 100
x3[0] = 100

print(f"\nAfter changing x3[0] = 100:")
print(f"x1 = {x1}")
print(f"x3 = {x3}")

# Confirming memory share again for clarity
print(f"Do x1 and x3 still share memory? {np.shares_memory(x1, x3)}")


Before change: x1 = [999 888  30  40  50]
Before change: x3 = [999 888  30  40  50]

After changing x3[0] = 100:
x1 = [100 888  30  40  50]
x3 = [100 888  30  40  50]
Do x1 and x3 still share memory? True


In [ ]:
#print x1 and x3 to check if changes reflected in both
import numpy as np

# Recreate the state of x1 and x3 after the last modification (x3[0] = 100)
# This assumes x1 started as [10, 20, 30, 40, 50], x3 was its view,
# and then x3[0] was set to 100 and x3[1] to 888.
x1 = np.array([10, 20, 30, 40, 50])
x3 = x1.view()
x3[0] = 100
x3[1] = 888 # This line was also present in prior steps, ensuring the state is accurate

print(f"Current x1: {x1}")
print(f"Current x3: {x3}")

# We can also re-confirm the memory share just to be absolutely clear
print(f"Do x1 and x3 share memory? {np.shares_memory(x1, x3)}")



Current x1: [100 888  30  40  50]
Current x3: [100 888  30  40  50]
Do x1 and x3 share memory? True


Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

# x4=
import numpy as np

# Create an original array x1 (let's use a fresh one for clear demonstration of copy)
x1 = np.array([10, 20, 30, 40, 50])
print(f"Original x1: {x1}")

# Create a COPY of x1 using the .copy() method
x4 = x1.copy()
print(f"x4 (a copy created with .copy()): {x4}")

# Check if they are the exact same object (should be False)
print(f"Are x1 and x4 the same object? {x1 is x4}")

# Check if they share the same underlying memory (should be False for a true copy)
print(f"Do x1 and x4 share the same memory? {np.shares_memory(x1, x4)}")

# Now, modify an element in x4 (the copy)
x4[0] = 999
x4[1] = 888

print(f"\nModified x4 (the copy): {x4}")
print(f"Original x1 after modifying x4: {x1}") # Observe: x1 remains unchanged!

# Modify an element in x1 (the original)
x1[2] = 777
print(f"\nModified x1 (the original): {x1}")
print(f"x4 after modifying x1: {x4}") # Observe: x4 remains unchanged!


Original x1: [10 20 30 40 50]
x4 (a copy created with .copy()): [10 20 30 40 50]
Are x1 and x4 the same object? False
Do x1 and x4 share the same memory? False

Modified x4 (the copy): [999 888  30  40  50]
Original x1 after modifying x4: [10 20 30 40 50]

Modified x1 (the original): [ 10  20 777  40  50]
x4 after modifying x1: [999 888  30  40  50]


In [ ]:
# Change the last element of x4 as 900
import numpy as np

# --- 1. Demonstrating a VIEW (shared data) using direct assignment ---
print("--- Demonstrating a VIEW (Shared Data - Direct Assignment) ---")

# Create the original array
x1_original_assignment = np.array([10, 20, 30, 40, 50])
print(f"Initial x1_original_assignment: {x1_original_assignment}")

# Create x2 as a VIEW of x1_original_assignment (direct assignment)
# x2_view_assignment now points to the same data as x1_original_assignment
x2_view_assignment = x1_original_assignment
print(f"x2_view_assignment (assigned as x1_original_assignment): {x2_view_assignment}")

# Verify if they are the exact same object (should be True)
print(f"Are x1_original_assignment and x2_view_assignment the same object? {x1_original_assignment is x2_view_assignment}")

# Check if they share the same underlying memory (should be True)
print(f"Do x1_original_assignment and x2_view_assignment share memory? {np.shares_memory(x1_original_assignment, x2_view_assignment)}")

# Modify an element in the view (x2_view_assignment)
print("\n--- Modifying the View (x2_view_assignment[0] = 999) ---")
x2_view_assignment[0] = 999
print(f"x2_view_assignment after modification: {x2_view_assignment}")
print(f"x1_original_assignment after x2_view_assignment modification: {x1_original_assignment}") # x1_original_assignment also changed!

# --- 2. Demonstrating a VIEW (shared data) using .view() method ---
print("\n--- Demonstrating a VIEW (Shared Data - .view() method) ---")

# Create a fresh original array for this demo part
x1_original_view_method = np.array([100, 200, 300, 400, 500])
print(f"Initial x1_original_view_method: {x1_original_view_method}")

# Create x3 as a VIEW of x1_original_view_method using .view() method
x3_view_method = x1_original_view_method.view()
print(f"x3_view_method (created with .view()): {x3_view_method}")

# Verify if they are the exact same object (should be False, unlike direct assignment)
print(f"Are x1_original_view_method and x3_view_method the same object? {x1_original_view_method is x3_view_method}")

# Check if they share the same underlying memory (should be True)
print(f"Do x1_original_view_method and x3_view_method share memory? {np.shares_memory(x1_original_view_method, x3_view_method)}")

# Modify an element in the view (x3_view_method)
print("\n--- Modifying the View (x3_view_method[0] = 777) ---")
x3_view_method[0] = 777
print(f"x3_view_method after modification: {x3_view_method}")
print(f"x1_original_view_method after x3_view_method modification: {x1_original_view_method}") # x1_original_view_method also changed!


# --- 3. Demonstrating a COPY (independent data) using .copy() method ---
print("\n--- Demonstrating a COPY (Independent Data - .copy() method) ---")

# Create a fresh original array for this demo part
x1_copy_original = np.array([1, 2, 3, 4, 5])
print(f"Initial x1_copy_original: {x1_copy_original}")

# Create x4 as a COPY of x1_copy_original using .copy() method
x4_copy = x1_copy_original.copy()
print(f"x4_copy (created with .copy()): {x4_copy}")

# Verify if they are the exact same object (should be False)
print(f"Are x1_copy_original and x4_copy the same object? {x1_copy_original is x4_copy}")

# Check if they share the same underlying memory (should be False for a true copy)
print(f"Do x1_copy_original and x4_copy share memory? {np.shares_memory(x1_copy_original, x4_copy)}")

# Modify an element in the copy (x4_copy) - Specifically changing the last element
print("\n--- Modifying the Copy (x4_copy[-1] = 900) ---")
x4_copy[-1] = 900 # Change the last element

print(f"x4_copy after modification: {x4_copy}")
print(f"x1_copy_original after x4_copy modification: {x1_copy_original}") # x1_copy_original remains unchanged!




--- Demonstrating a VIEW (Shared Data - Direct Assignment) ---
Initial x1_original_assignment: [10 20 30 40 50]
x2_view_assignment (assigned as x1_original_assignment): [10 20 30 40 50]
Are x1_original_assignment and x2_view_assignment the same object? True
Do x1_original_assignment and x2_view_assignment share memory? True

--- Modifying the View (x2_view_assignment[0] = 999) ---
x2_view_assignment after modification: [999  20  30  40  50]
x1_original_assignment after x2_view_assignment modification: [999  20  30  40  50]

--- Demonstrating a VIEW (Shared Data - .view() method) ---
Initial x1_original_view_method: [100 200 300 400 500]
x3_view_method (created with .view()): [100 200 300 400 500]
Are x1_original_view_method and x3_view_method the same object? False
Do x1_original_view_method and x3_view_method share memory? True

--- Modifying the View (x3_view_method[0] = 777) ---
x3_view_method after modification: [777 200 300 400 500]
x1_original_view_method after x3_view_method mod

In [ ]:
# print both x1 and x4 to check if changes reflected in both
import numpy as np

# Recreate the scenario: x4 is a copy of x1, and x4's last element was changed.
# This ensures we are showing the state immediately after the last operation.
x1 = np.array([10, 20, 30, 40, 50]) # Original state of x1
x4 = x1.copy()                       # x4 is an independent copy
x4[-1] = 900                         # Modify x4, x1 should NOT change

print(f"Current x1: {x1}")
print(f"Current x4: {x4}")

# Confirming memory share one more time for clarity
print(f"Do x1 and x4 share memory? {np.shares_memory(x1, x4)}")




Current x1: [10 20 30 40 50]
Current x4: [ 10  20  30  40 900]
Do x1 and x4 share memory? False


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:
#Check memory share between x1 and x4
import numpy as np

# --- Understanding NumPy Views vs. Copies ---

print("This code demonstrates the difference between NumPy views and copies.")
print("A view shares data with the original array; a copy has independent data.\n")


# --- PART 1: Demonstrating a VIEW (Shared Data) ---
# A view is created when you slice an array, or assign one array to another (like x2 = x1),
# or explicitly use the .view() method. Views do NOT own their data.

print("--- DEMONSTRATING VIEWS (SHARED DATA) ---")

# Scenario 1a: View created by direct assignment (x2 = x1)
print("\n--- View Scenario 1a: Direct Assignment (x2 = x1) ---")
x1_original_assignment = np.array([1, 2, 3, 4, 5])
print(f"1a. Initial x1_original_assignment: {x1_original_assignment}")

x2_view_assignment = x1_original_assignment # x2_view_assignment is now a view of x1_original_assignment
print(f"1a. x2_view_assignment (assigned as x1_original_assignment): {x2_view_assignment}")

# Check if they are the exact same object (should be True for direct assignment)
print(f"1a. Are x1_original_assignment and x2_view_assignment the same object? {x1_original_assignment is x2_view_assignment}")

# Check if they share the same underlying memory (should be True)
print(f"1a. Do x1_original_assignment and x2_view_assignment share memory? {np.shares_memory(x1_original_assignment, x2_view_assignment)}")

# Modify an element in the view and observe the original
print("\n1a. Modifying x2_view_assignment[0] = 999...")
x2_view_assignment[0] = 999
print(f"1a. x2_view_assignment after modification: {x2_view_assignment}")
print(f"1a. x1_original_assignment after x2_view_assignment modification: {x1_original_assignment}") # x1_original_assignment also changed!


# Scenario 1b: View created by .view() method
print("\n--- View Scenario 1b: Using .view() Method (x3 = x1.view()) ---")
x1_original_view_method = np.array([100, 200, 300, 400, 500]) # Fresh array for clarity
print(f"1b. Initial x1_original_view_method: {x1_original_view_method}")

x3_view_method = x1_original_view_method.view() # x3_view_method is now a view of x1_original_view_method
print(f"1b. x3_view_method (created with .view()): {x3_view_method}")

# Check if they are the exact same object (should be False



This code demonstrates the difference between NumPy views and copies.
A view shares data with the original array; a copy has independent data.

--- DEMONSTRATING VIEWS (SHARED DATA) ---

--- View Scenario 1a: Direct Assignment (x2 = x1) ---
1a. Initial x1_original_assignment: [1 2 3 4 5]
1a. x2_view_assignment (assigned as x1_original_assignment): [1 2 3 4 5]
1a. Are x1_original_assignment and x2_view_assignment the same object? True
1a. Do x1_original_assignment and x2_view_assignment share memory? True

1a. Modifying x2_view_assignment[0] = 999...
1a. x2_view_assignment after modification: [999   2   3   4   5]
1a. x1_original_assignment after x2_view_assignment modification: [999   2   3   4   5]

--- View Scenario 1b: Using .view() Method (x3 = x1.view()) ---
1b. Initial x1_original_view_method: [100 200 300 400 500]
1b. x3_view_method (created with .view()): [100 200 300 400 500]


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [ ]:
# stack x1 and x4 along columns.
import numpy as np

# --- Stacking Arrays: hstack() vs. vstack() ---

print("Stacking arrays is similar to concatenation but along a new axis.")
print("NumPy provides helper functions for different stacking directions.\n")

# --- hstack(): Stacking along rows (horizontal stacking) ---
# This function stacks arrays in sequence horizontally (column-wise).
# For 1-D arrays, it essentially concatenates them side-by-side.
# For 2-D arrays, it joins them column by column.

print("--- np.hstack(): Stacking Horizontally (along columns for rows) ---")

# Example with 1D arrays
arr1_1d_h = np.array([1, 2, 3])
arr2_1d_h = np.array([4, 5, 6])
print(f"Original arr1_1d_h: {arr1_1d_h}")
print(f"Original arr2_1d_h: {arr2_1d_h}")

stacked_horizontal_1d = np.hstack((arr1_1d_h, arr2_1d_h))
print(f"Stacked horizontally (1D arrays): {stacked_horizontal_1d}")
# Result: [1 2 3 4 5 6] - effectively concatenation

# Example with 2D arrays
arr1_2d_h = np.array([[1, 2], [3, 4]])
arr2_2d_h = np.array([[5, 6], [7, 8]])
print(f"\nOriginal arr1_2d_h:\n{arr1_2d_h}")
print(f"Original arr2_2d_h:\n{arr2_2d_h}")

stacked_horizontal_2d = np.hstack((arr1_2d_h, arr2_2d_h))
print(f"Stacked horizontally (2D arrays):\n{stacked_horizontal_2d}")
# Result:
# [[1 2 5 6]
#  [3 4 7 8]]


# --- vstack(): Stacking along columns (vertical stacking) ---
# This function stacks arrays in sequence vertically (row-wise).
# For 1-D arrays, it converts them into 2-D rows and stacks them on top of each other.
# For 2-D arrays, it joins them row by row.

print("\n--- np.vstack(): Stacking Vertically (along rows for columns) ---")

# Example with 1D arrays (as requested in the previous turn)
x1 = np.array([1, 2, 3])
x4 = np.array([4, 5, 6])
print(f"Original x1: {x1}")
print(f"Original x4: {x4}")

stacked_columns = np.vstack((x1, x4))
print(f"Stacked x1 and x4 along columns (using vstack()):\n{stacked_columns}")
# Result:
# [[1 2 3]
#  [4 5 6]]

# Example with 2D arrays
arr1_2d_v = np.array([[10, 11], [12, 13]])
arr2_2d_v = np.array([[14, 15], [16, 17]])
print(f"\nOriginal arr1_2d_v:\n{arr1_2d_v}")
print(f"Original arr2_2d_v:\n{arr2_2d_v}")

stacked_vertical_2d = np.vstack((arr1_2d_v, arr2_2d_v))
print(f"Stacked vertically (2D arrays):\n{stacked_vertical_2d}")
# Result:
# [[10 11]
#  [12 13]
#  [14 15]
#  [16 17]]


Stacking arrays is similar to concatenation but along a new axis.
NumPy provides helper functions for different stacking directions.

--- np.hstack(): Stacking Horizontally (along columns for rows) ---
Original arr1_1d_h: [1 2 3]
Original arr2_1d_h: [4 5 6]
Stacked horizontally (1D arrays): [1 2 3 4 5 6]

Original arr1_2d_h:
[[1 2]
 [3 4]]
Original arr2_2d_h:
[[5 6]
 [7 8]]
Stacked horizontally (2D arrays):
[[1 2 5 6]
 [3 4 7 8]]

--- np.vstack(): Stacking Vertically (along rows for columns) ---
Original x1: [1 2 3]
Original x4: [4 5 6]
Stacked x1 and x4 along columns (using vstack()):
[[1 2 3]
 [4 5 6]]

Original arr1_2d_v:
[[10 11]
 [12 13]]
Original arr2_2d_v:
[[14 15]
 [16 17]]
Stacked vertically (2D arrays):
[[10 11]
 [12 13]
 [14 15]
 [16 17]]


In [ ]:
#stack x1 and x4 along rows
import numpy as np

# --- Stacking Arrays in NumPy ---

print("This code demonstrates how to stack NumPy arrays using hstack() and vstack().\n")

# --- 1. np.hstack(): Stacking Horizontally (along columns) ---
# hstack() concatenates arrays column-wise, effectively adding new columns.
# For 1D arrays, it simply joins them end-to-end.

print("--- np.hstack(): Horizontal Stacking (along rows/columns) ---")

# Example 1.1: Stacking 1D arrays horizontally
arr1_h_1d = np.array([1, 2, 3])
arr2_h_1d = np.array([4, 5, 6])
print(f"Original arr1_h_1d: {arr1_h_1d}")
print(f"Original arr2_h_1d: {arr2_h_1d}")

stacked_h_1d = np.hstack((arr1_h_1d, arr2_h_1d))
print(f"Stacked horizontally (1D arrays): {stacked_h_1d}")
# Output: [1 2 3 4 5 6]

# Example 1.2: Stacking 2D arrays horizontally
arr1_h_2d = np.array([[10, 11], [12, 13]])
arr2_h_2d = np.array([[14, 15], [16, 17]])
print(f"\nOriginal arr1_h_2d:\n{arr1_h_2d}")
print(f"Original arr2_h_2d:\n{arr2_h_2d}")

stacked_h_2d = np.hstack((arr1_h_2d, arr2_h_2d))
print(f"Stacked horizontally (2D arrays):\n{stacked_h_2d}")
# Output:
# [[10 11 14 15]
#  [12 13 16 17]]


# --- 2. np.vstack(): Stacking Vertically (along rows) ---
# vstack() concatenates arrays row-wise, effectively adding new rows.
# For 1D arrays, it converts them into 2D rows and stacks them on top of each other.

print("\n--- np.vstack(): Vertical Stacking (along columns/rows) ---")

# Example 2.1: Stacking 1D arrays vertically (as requested previously with x1 and x4)
x1_v_1d = np.array([1, 2, 3])
x4_v_1d = np.array([4, 5, 6])
print(f"Original x1_v_1d: {x1_v_1d}")
print(f"Original x4_v_1d: {x4_v_1d}")

stacked_v_1d = np.vstack((x1_v_1d, x4_v_1d))
print(f"Stacked vertically (1D arrays - along columns): \n{stacked_v_1d}")
# Output:
# [[1 2 3]
#  [4 5 6]]

# Example 2.2: Stacking 2D arrays vertically
arr1_v_2d = np.array([[20, 21], [22, 23]])
arr2_v_2d = np.array([[24, 25], [26, 27]])
print(f"\nOriginal arr1_v_2d:\n{arr1_v_2d}")
print(f"Original arr2_v_2d:\n{arr2_v_2d}")

stacked_v_2d = np.vstack((arr1_v_2d, arr2_v_2d))
print(f"Stacked vertically (2D arrays):\n{stacked_v_2d}")
# Output:
# [[20 21]
#  [22 23]
#  [24 25]
#  [26 27]]


This code demonstrates how to stack NumPy arrays using hstack() and vstack().

--- np.hstack(): Horizontal Stacking (along rows/columns) ---
Original arr1_h_1d: [1 2 3]
Original arr2_h_1d: [4 5 6]
Stacked horizontally (1D arrays): [1 2 3 4 5 6]

Original arr1_h_2d:
[[10 11]
 [12 13]]
Original arr2_h_2d:
[[14 15]
 [16 17]]
Stacked horizontally (2D arrays):
[[10 11 14 15]
 [12 13 16 17]]

--- np.vstack(): Vertical Stacking (along columns/rows) ---
Original x1_v_1d: [1 2 3]
Original x4_v_1d: [4 5 6]
Stacked vertically (1D arrays - along columns): 
[[1 2 3]
 [4 5 6]]

Original arr1_v_2d:
[[20 21]
 [22 23]]
Original arr2_v_2d:
[[24 25]
 [26 27]]
Stacked vertically (2D arrays):
[[20 21]
 [22 23]
 [24 25]
 [26 27]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [ ]:
# arr1 =


# arr2 =


##join arr1 and arr2 along rows using concatenate() function

import numpy as np

# Define arr1 and arr2 (using 2D arrays to clearly demonstrate axis=1 concatenation)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"Original arr1:\n{arr1}")
print(f"Original arr2:\n{arr2}")

# Join arr1 and arr2 along rows using concatenate() function (axis=1)
# This means it will join them column-wise, extending horizontally.
concatenated_along_rows = np.concatenate((arr1, arr2), axis=1)

print(f"\nJoined arr1 and arr2 along rows (axis=1) using concatenate():\n{concatenated_along_rows}")


Original arr1:
[[1 2]
 [3 4]]
Original arr2:
[[5 6]
 [7 8]]

Joined arr1 and arr2 along rows (axis=1) using concatenate():
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
##join arr1 and arr2 along columns using concatenate() function
import numpy as np

# --- Understanding np.concatenate() ---

print("The np.concatenate() function is a versatile way to join arrays along a specified axis.")
print("If 'axis' is not explicitly passed, it defaults to 0 (column-wise or vertical stacking).\n")

# Define sample 2D arrays for demonstration
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

print(f"Original arr1:\n{arr1}")
print(f"Original arr2:\n{arr2}")


# --- 1. Joining along rows (axis=1) ---
# This is equivalent to horizontal stacking, similar to np.hstack().
# It adds arrays side-by-side.

print("\n--- Joining along Rows (axis=1) using concatenate() ---")
concatenated_along_rows = np.concatenate((arr1, arr2), axis=1)

print(f"Joined arr1 and arr2 along rows (axis=1):\n{concatenated_along_rows}")
# Expected Output:
# [[1 2 5 6]
#  [3 4 7 8]]


# --- 2. Joining along columns (axis=0) ---
# This is equivalent to vertical stacking, similar to np.vstack().
# It stacks arrays on top of each other.

print("\n--- Joining along Columns (axis=0) using concatenate() ---")
concatenated_along_columns = np.concatenate((arr1, arr2), axis=0)

print(f"Joined arr1 and arr2 along columns (axis=0):\n{concatenated_along_columns}")
# Expected Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]


# --- Fun Fact: Default axis ---
print("\n--- Fun Fact: Default Axis (axis=0) ---")
# If axis is not specified, it defaults to 0 (along columns).
concatenated_default_axis = np.concatenate((arr1, arr2))
print(f"Joined arr1 and arr2 with default axis (axis=0):\n{concatenated_default_axis}")

print("\nIn summary:")
print("- `np.concatenate((arr1, arr2), axis=0)` is like `np.vstack((arr1, arr2))`.")
print("- `np.concatenate((arr1, arr2), axis=1)` is like `np.hstack((arr1, arr2))`.")


The np.concatenate() function is a versatile way to join arrays along a specified axis.
If 'axis' is not explicitly passed, it defaults to 0 (column-wise or vertical stacking).

Original arr1:
[[1 2]
 [3 4]]
Original arr2:
[[5 6]
 [7 8]]

--- Joining along Rows (axis=1) using concatenate() ---
Joined arr1 and arr2 along rows (axis=1):
[[1 2 5 6]
 [3 4 7 8]]

--- Joining along Columns (axis=0) using concatenate() ---
Joined arr1 and arr2 along columns (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

--- Fun Fact: Default Axis (axis=0) ---
Joined arr1 and arr2 with default axis (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In summary:
- `np.concatenate((arr1, arr2), axis=0)` is like `np.vstack((arr1, arr2))`.
- `np.concatenate((arr1, arr2), axis=1)` is like `np.hstack((arr1, arr2))`.


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:
# append arr2 to arr1
import numpy as np

# Define arr1 and arr2 (using the 2D arrays from our concatenate examples for consistency)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"Original arr1:\n{arr1}")
print(f"Original arr2:\n{arr2}")

# Append arr2 to arr1 using append() function (no axis specified, so arrays are flattened)
appended_array_default = np.append(arr1, arr2)

print(f"\nAppended arr2 to arr1 (default behavior - flattened):\n{appended_array_default}")
print(f"Shape of appended_array_default: {appended_array_default.shape}")

# --- Important Note on np.append() for Multi-dimensional Arrays ---
# While it can flatten, for stacking (adding rows or columns),
# it's usually more intuitive to use axis=0 or axis=1.

# Appending along axis=0 (adding rows vertically)
# The second array must have the same number of columns as the first.
appended_array_axis_0 = np.append(arr1, arr2, axis=0)
print(f"\nAppended arr2 to arr1 along axis=0 (adding rows):\n{appended_array_axis_0}")
print(f"Shape of appended_array_axis_0: {appended_array_axis_0.shape}")

# Appending along axis=1 (adding columns horizontally)
# The second array must have the same number of rows as the first.
appended_array_axis_1 = np.append(arr1, arr2, axis=1)
print(f"\nAppended arr2 to arr1 along axis=1 (adding columns):\n{appended_array_axis_1}")
print(f"Shape of appended_array_axis_1: {appended_array_axis_1.shape}")


Original arr1:
[[1 2]
 [3 4]]
Original arr2:
[[5 6]
 [7 8]]

Appended arr2 to arr1 (default behavior - flattened):
[1 2 3 4 5 6 7 8]
Shape of appended_array_default: (8,)

Appended arr2 to arr1 along axis=0 (adding rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape of appended_array_axis_0: (4, 2)

Appended arr2 to arr1 along axis=1 (adding columns):
[[1 2 5 6]
 [3 4 7 8]]
Shape of appended_array_axis_1: (2, 4)


Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
import numpy as np

# --- Manipulating Elements in NumPy Arrays (Add, Insert, Delete) ---

print("This code demonstrates how to add, insert, and delete elements in NumPy arrays.")
print("Remember that these operations typically return a *new* array, rather than modifying in place.\n")

# --- 1. Adding/Appending Elements using np.append() ---
# This function appends values to the end of an array.
# By default (no axis), it flattens input arrays.
# With an axis, it appends along that dimension.

print("--- 1. np.append(): Adding/Appending Elements ---")

# Example 1.1: Appending 1D arrays (default behavior - flattening)
arr_append_1d_a = np.array([10, 20, 30])
arr_append_1d_b = np.array([40, 50])
print(f"Original arr_append_1d_a: {arr_append_1d_a}")
print(f"Original arr_append_1d_b: {arr_append_1d_b}")

appended_result_default = np.append(arr_append_1d_a, arr_append_1d_b)
print(f"Appended (default, flattened): {appended_result_default}")

# Example 1.2: Appending 2D arrays along axis=0 (adding rows)
arr_append_2d_a = np.array([[1, 2], [3, 4]])
arr_append_2d_b = np.array([[5, 6]]) # Must match column count
print(f"\nOriginal arr_append_2d_a:\n{arr_append_2d_a}")
print(f"Original arr_append_2d_b:\n{arr_append_2d_b}")

appended_result_axis0 = np.append(arr_append_2d_a, arr_append_2d_b, axis=0)
print(f"Appended (axis=0 - adding rows):\n{appended_result_axis0}")

# Example 1.3: Appending 2D arrays along axis=1 (adding columns)
arr_append_2d_c = np.array([[10, 11], [12, 13]])
arr_append_2d_d = np.array([[14], [15]]) # Must match row count
print(f"\nOriginal arr_append_2d_c:\n{arr_append_2d_c}")
print(f"Original arr_append_2d_d:\n{arr_append_2d_d}")

appended_result_axis1 = np.append(arr_append_2d_c, arr_append_2d_d, axis=1)
print(f"Appended (axis=1 - adding columns):\n{appended_result_axis1}")


# --- 2. Inserting Elements using np.insert() ---
# This function inserts values into an array before a specified index.
# It also returns a new array.

print("\n--- 2. np.insert(): Inserting Elements ---")

# Example 2.1: Inserting into a 1D array
arr_insert_1d = np.array([10, 20, 30, 40, 50])
elements_to_insert_1d = np.array([99, 88])
insert_index = 2 # Insert before index 2 (i.e., between 20 and 30)

print(f"Original arr_insert_1d: {arr_insert_1d}")
print(f"Elements to insert: {elements_to_insert_1d} at index {insert_index}")

inserted_result_1d = np.insert(arr_insert_1d, insert_index, elements_to_insert_1d)
print(f"Array after insertion: {inserted_result_1d}")

# Example 2.2: Inserting a row into a 2D array (axis=0)
arr_insert_2d = np.array([[1, 2], [3, 4], [5, 6]])
row_to_insert = np.array([9, 9])
insert_row_index = 1 # Insert before row with index 1

print(f"\nOriginal arr_insert_2d:\n{arr_insert_2d}")
print(f"Row to insert: {row_to_insert} at row index {insert_row_index}")

inserted_result_2d_row = np.insert(arr_insert_2d, insert_row_index, row_to_insert, axis=0)
print(f"Array after inserting row (axis=0):\n{inserted_result_2d_row}")

# Example 2.3: Inserting a column into a 2D array (axis=1)
column_to_insert = np.array([7, 7, 7])
insert_col_index = 0 # Insert before column with index 0

print(f"\nOriginal arr_insert_2d:\n{arr_insert_2d}") # Re-using original for demo
print(f"Column to insert: {column_to_insert} at column index {insert_col_index}")

inserted_result_2d_col = np.insert(arr_insert_2d, insert_col_index, column_to_insert, axis=1)
print(f"Array after inserting column (axis=1):\n{inserted_result_2d_col}")


# --- 3. Deleting Elements using np.delete() ---
# This function returns a new array with specified elements/sub-arrays deleted.

print("\n--- 3. np.delete(): Deleting Elements ---")

# Example 3.1: Deleting from a 1D array
arr_delete_1d = np.array([10, 20, 30, 40, 50])
delete_index_1d = 2 # Delete element at index 2 (which is 30)

print(f"Original arr_delete_1d: {arr_delete_1d}")
print(f"Index to delete: {delete_index_1d}")

deleted_result_1d = np.delete(arr_delete_1d, delete_index_1d)
print(f"Array after deletion: {deleted_result_1d}")

# Example 3.2: Deleting multiple elements from a 1D array
delete_indices_1d_multiple = [0, 4] # Delete elements at index 0 (10) and 4 (50)
print(f"\nOriginal arr_delete_1d: {arr_delete_1d}") # Use original again
print(f"Indices to delete: {delete_indices_1d_multiple}")

deleted_result_1d_multiple = np.delete(arr_delete_1d, delete_indices_1d_multiple)
print(f"Array after multiple deletions: {deleted_result_1d_multiple}")


# Example 3.3: Deleting a row from a 2D array (axis=0)
arr_delete_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
delete_row_index = 1 # Delete row at index 1 ([4, 5, 6])

print(f"\nOriginal arr_delete_2d:\n{arr_delete_2d}")
print(f"Row index to delete: {delete_row_index}")

deleted_result_2d_row = np.delete(arr_delete_2d, delete_row_index, axis=0)
print(f"Array after deleting row (axis=0):\n{deleted_result_2d_row}")

# Example 3.4: Deleting a column from a 2D array (axis=1)
delete_col_index = 2 # Delete column at index 2 ([3, 6, 9])

print(f"\nOriginal arr_delete_2d:\n{arr_delete_2d}") # Use original again
print(f"Column index to delete: {delete_col_index}")

deleted_result_2d_col = np.delete(arr_delete_2d, delete_col_index, axis=1)
print(f"Array after deleting column (axis=1):\n{deleted_result_2d_col}")


This code demonstrates how to add, insert, and delete elements in NumPy arrays.
Remember that these operations typically return a *new* array, rather than modifying in place.

--- 1. np.append(): Adding/Appending Elements ---
Original arr_append_1d_a: [10 20 30]
Original arr_append_1d_b: [40 50]
Appended (default, flattened): [10 20 30 40 50]

Original arr_append_2d_a:
[[1 2]
 [3 4]]
Original arr_append_2d_b:
[[5 6]]
Appended (axis=0 - adding rows):
[[1 2]
 [3 4]
 [5 6]]

Original arr_append_2d_c:
[[10 11]
 [12 13]]
Original arr_append_2d_d:
[[14]
 [15]]
Appended (axis=1 - adding columns):
[[10 11 14]
 [12 13 15]]

--- 2. np.insert(): Inserting Elements ---
Original arr_insert_1d: [10 20 30 40 50]
Elements to insert: [99 88] at index 2
Array after insertion: [10 20 99 88 30 40 50]

Original arr_insert_2d:
[[1 2]
 [3 4]
 [5 6]]
Row to insert: [9 9] at row index 1
Array after inserting row (axis=0):
[[1 2]
 [9 9]
 [3 4]
 [5 6]]

Original arr_insert_2d:
[[1 2]
 [3 4]
 [5 6]]
Column to ins

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2
import numpy as np

# --- Manipulating Elements in NumPy Arrays (Add, Insert, Delete) ---

print("This code demonstrates how to add, insert, and delete elements in NumPy arrays.")
print("Remember that these operations typically return a *new* array, rather than modifying in place.\n")

# --- 1. Adding/Appending Elements using np.append() ---
# This function appends values to the end of an array.
# By default (no axis), it flattens input arrays.
# With an axis, it appends along that dimension.

print("--- 1. np.append(): Adding/Appending Elements ---")

# Example 1.1: Appending 1D arrays (default behavior - flattening)
arr_append_1d_a = np.array([10, 20, 30])
arr_append_1d_b = np.array([40, 50])
print(f"Original arr_append_1d_a: {arr_append_1d_a}")
print(f"Original arr_append_1d_b: {arr_append_1d_b}")

appended_result_default = np.append(arr_append_1d_a, arr_append_1d_b)
print(f"Appended (default, flattened): {appended_result_default}")

# Example 1.2: Appending 2D arrays along axis=0 (adding rows)
arr_append_2d_a = np.array([[1, 2], [3, 4]])
arr_append_2d_b = np.array([[5, 6]]) # Must match column count
print(f"\nOriginal arr_append_2d_a:\n{arr_append_2d_a}")
print(f"Original arr_append_2d_b:\n{arr_append_2d_b}")

appended_result_axis0 = np.append(arr_append_2d_a, arr_append_2d_b, axis=0)
print(f"Appended (axis=0 - adding rows):\n{appended_result_axis0}")

# Example 1.3: Appending 2D arrays along axis=1 (adding columns)
arr_append_2d_c = np.array([[10, 11], [12, 13]])
arr_append_2d_d = np.array([[14], [15]]) # Must match row count
print(f"\nOriginal arr_append_2d_c:\n{arr_append_2d_c}")
print(f"Original arr_append_2d_d:\n{arr_append_2d_d}")

appended_result_axis1 = np.append(arr_append_2d_c, arr_append_2d_d, axis=1)
print(f"Appended (axis=1 - adding columns):\n{appended_result_axis1}")


# --- 2. Inserting Elements using np.insert() ---
# This function inserts values into an array before a specified index.
# It also returns a new array.

print("\n--- 2. np.insert(): Inserting Elements ---")

# Example 2.1: Inserting into a 1D array
arr_insert_1d = np.array([10, 20, 30, 40, 50])
elements_to_insert_1d = np.array([99, 88])
insert_index = 2 # Insert before index 2 (i.e., between 20 and 30)

print(f"Original arr_insert_1d: {arr_insert_1d}")
print(f"Elements to insert: {elements_to_insert_1d} at index {insert_index}")

inserted_result_1d = np.insert(arr_insert_1d, insert_index, elements_to_insert_1d)
print(f"Array after insertion: {inserted_result_1d}")

# Example 2.2: Inserting a row into a 2D array (axis=0)
arr_insert_2d = np.array([[1, 2], [3, 4], [5, 6]])
row_to_insert = np.array([9, 9])
insert_row_index = 1 # Insert before row with index 1

print(f"\nOriginal arr_insert_2d:\n{arr_insert_2d}")
print(f"Row to insert: {row_to_insert} at row index {insert_row_index}")

inserted_result_2d_row = np.insert(arr_insert_2d, insert_row_index, row_to_insert, axis=0)
print(f"Array after inserting row (axis=0):\n{inserted_result_2d_row}")

# Example 2.3: Inserting a column into a 2D array (axis=1)
column_to_insert = np.array([7, 7, 7])
insert_col_index = 0 # Insert before column with index 0

print(f"\nOriginal arr_insert_2d:\n{arr_insert_2d}") # Re-using original for demo
print(f"Column to insert: {column_to_insert} at column index {insert_col_index}")

inserted_result_2d_col = np.insert(arr_insert_2d, insert_col_index, column_to_insert, axis=1)
print(f"Array after inserting column (axis=1):\n{inserted_result_2d_col}")


# --- 3. Deleting Elements using np.delete() ---
# This function returns a new array with specified elements/sub-arrays deleted.

print("\n--- 3. np.delete(): Deleting Elements ---")

# Example 3.1: Deleting a single element from a 1D array (2nd element of x2)
x2_delete_example = np.array([10, 20, 30, 40, 50])
delete_index_1d = 1 # Delete element at index 1 (which is 20)

print(f"Original x2_delete_example: {x2_delete_example}")
print(f"Index to delete (2nd element): {delete_index_1d}")

deleted_result_1d = np.delete(x2_delete_example, delete_index_1d)
print(f"Array after deleting the 2nd element: {deleted_result_1d}")

# Example 3.2: Deleting multiple elements from a 1D array
arr_delete_1d_multiple = np.array([10, 20, 30, 40, 50])
delete_indices_1d_multiple = [0, 3] # Delete elements at index 0 (10) and 3 (40)
print(f"\nOriginal arr_delete_1d_multiple: {arr_delete_1d_multiple}")
print(f"Indices to delete: {delete_indices_1d_multiple}")

deleted_result_1d_multiple = np.delete(arr_delete_1d_multiple, delete_indices_1d_multiple)
print(f"Array after multiple deletions: {deleted_result_1d_multiple}")


# Example 3.3: Deleting a row from a 2D array (axis=0)
arr_delete_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
delete_row_index = 1 # Delete row at index 1 ([4, 5, 6])

print(f"\nOriginal arr_delete_2d:\n{arr_delete_2d}")
print(f"Row index to delete: {delete_row_index}")

deleted_result_2d_row = np.delete(arr_delete_2d, delete_row_index, axis=0)
print(f"Array after deleting row (axis=0):\n{deleted_result_2d_row}")

# Example 3.4: Deleting a column from a 2D array (axis=1)
delete_col_index = 2 # Delete column at index 2 ([3, 6, 9])

print(f"\nOriginal arr_delete_2d:\n{arr_delete_2d}") # Use original again
print(f"Column index to delete: {delete_col_index}")

deleted_result_2d_col = np.delete(arr_delete_2d, delete_col_index, axis=1)
print(f"Array after deleting column (axis=1):\n{deleted_result_2d_col}")



This code demonstrates how to add, insert, and delete elements in NumPy arrays.
Remember that these operations typically return a *new* array, rather than modifying in place.

--- 1. np.append(): Adding/Appending Elements ---
Original arr_append_1d_a: [10 20 30]
Original arr_append_1d_b: [40 50]
Appended (default, flattened): [10 20 30 40 50]

Original arr_append_2d_a:
[[1 2]
 [3 4]]
Original arr_append_2d_b:
[[5 6]]
Appended (axis=0 - adding rows):
[[1 2]
 [3 4]
 [5 6]]

Original arr_append_2d_c:
[[10 11]
 [12 13]]
Original arr_append_2d_d:
[[14]
 [15]]
Appended (axis=1 - adding columns):
[[10 11 14]
 [12 13 15]]

--- 2. np.insert(): Inserting Elements ---
Original arr_insert_1d: [10 20 30 40 50]
Elements to insert: [99 88] at index 2
Array after insertion: [10 20 99 88 30 40 50]

Original arr_insert_2d:
[[1 2]
 [3 4]
 [5 6]]
Row to insert: [9 9] at row index 1
Array after inserting row (axis=0):
[[1 2]
 [9 9]
 [3 4]
 [5 6]]

Original arr_insert_2d:
[[1 2]
 [3 4]
 [5 6]]
Column to ins

Did you see? 2 value is deleted from x2 which was at index position 2

Yes

Good Job learner!